[package]
name = "hardcpy"
version = "0.1.0"
edition = "2021"

[dependencies]
colored = "2.1.0"
dirs = "5.0.1"
fnv = "1.0.7"
rust-ini = "0.21.0"
indicatif = "0.17.8"
indicatif-log-bridge = "0.2.2"
colog = "1.3.0"
log = "0.4.22"
